/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apps;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dbss037
 */
public class transProduk extends javax.swing.JFrame {

    private Connection con;

    /**
     * Creates new form transProduk
     */
    public transProduk() throws ClassNotFoundException, SQLException {
        initComponents();
        connection();
    }

    public void connection() throws ClassNotFoundException, SQLException {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=amirashop;integratedSecurity=true;");
    }

    private void clearFields() {
        idProduk.setText(null);
        namaProduk.setText(null);
        hargaProduk.setText(null);
        diskon.setText(null);
        jumlahProduk.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idKasir = new javax.swing.JTextField();
        idProduk = new javax.swing.JTextField();
        namaProduk = new javax.swing.JTextField();
        hargaProduk = new javax.swing.JTextField();
        diskon = new javax.swing.JTextField();
        jumlahProduk = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Transaksi = new javax.swing.JTable();
        cekDiskon = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID_KASIR");

        jLabel2.setText("ID_PRODUK");

        jLabel3.setText("NAMA_PRODUK");

        jLabel4.setText("HARGA_PRODUK");

        jLabel5.setText("DISKON");

        jLabel6.setText("JUMLAH_PRODUK");

        idProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProdukActionPerformed(evt);
            }
        });
        idProduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idProdukKeyPressed(evt);
            }
        });

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tanggal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanggalMouseClicked(evt);
            }
        });

        jLabel7.setText("TANGGAL");

        Transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_PRODUK", "NAMA_PRODUK", "HARGA_PRODUK", "JUMLAH_PRODUK", "DISKON", "TOTAL_HARGA"
            }
        ));
        jScrollPane1.setViewportView(Transaksi);

        cekDiskon.setText("CEK DISKON");
        cekDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekDiskonActionPerformed(evt);
            }
        });

        jButton2.setText("TOTAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idProduk)
                    .addComponent(namaProduk)
                    .addComponent(hargaProduk)
                    .addComponent(diskon)
                    .addComponent(jumlahProduk)
                    .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cekDiskon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(idKasir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(namaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(hargaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jumlahProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cekDiskon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(0, 55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    public double getSum() {
        int rowsCount = Transaksi.getRowCount();
        double sum = 0;
        for (int i = 0; i < rowsCount; i++) {
            sum += Double.parseDouble((Transaksi.getValueAt(i, 5).toString()));
        }
        return sum;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Transaksi.getModel();
        String sql = "insert into penjualan_produk (ID_kasir, ID_Pr, nama_produk, harga_produk, jml_Pr)"
                + "values(?,?,?,?,?)";
        double subDiskon = Double.parseDouble(hargaProduk.getText()) * Double.parseDouble(jumlahProduk.getText())
                * (Double.parseDouble(diskon.getText()) / 100);
        double hasil = Double.parseDouble(hargaProduk.getText()) * Double.parseDouble(jumlahProduk.getText()) - subDiskon;
        model.addRow(new Object[]{idProduk.getText(), namaProduk.getText(), hargaProduk.getText(),
            jumlahProduk.getText(), diskon.getText(), hasil});
        PreparedStatement pst;
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, idKasir.getText());
            pst.setString(2, idProduk.getText());
            pst.setString(3, namaProduk.getText());
            pst.setString(4, hargaProduk.getText());
            pst.setString(5, jumlahProduk.getText());
            pst.execute();
            String sql2 = "update dbo.Produk set jml_Pr=produk.jml_Pr-" + jumlahProduk.getText() + "from dbo.penjualan_produk where dbo.Produk.ID_Pr='" + idProduk.getText() + "'";
            Statement pst2;
            pst2 = con.createStatement();
            pst2.addBatch(sql2);
            pst2.executeBatch();
            JOptionPane.showMessageDialog(null, "Success");
            clearFields();
        } catch (SQLException ex) {
            Logger.getLogger(transProduk.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void tanggalMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void cekDiskonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String sql3 = "select * from diskon,Produk where diskon.ID_Pr='" + idProduk.getText() + "'";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(tanggal.getDate());
        try {
            PreparedStatement pst = con.prepareStatement(sql3);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String a = rs.getString("tgl_disk");
                String b = rs.getString("ID_Pr");
                if (date.equals(a)) {
                    diskon.setText(String.valueOf(rs.getInt("jml_disk")));
                } else {
                    diskon.setText(null);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(transProduk.class.getName()).log(Level.SEVERE, null, ex);
        }

    }                                         

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        total.setText(Double.toString(getSum()));
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.hide();
        Transaksi back;
        back = new Transaksi();
        back.setVisible(true);
    }                                        

    private void idProdukActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void idProdukKeyPressed(java.awt.event.KeyEvent evt) {                                    
        // TODO add your handling code here:       
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String sql3 = "Select * from Produk where ID_Pr=?";
            try {
                PreparedStatement pst = con.prepareStatement(sql3);
                pst.setString(1, idProduk.getText());
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    String nama_Pr = rs.getString("nama_Pr");
                    String harga_Pr = rs.getString("harga_Pr");
                    namaProduk.setText(nama_Pr);
                    hargaProduk.setText(harga_Pr);
                }else{
                    JOptionPane.showMessageDialog(null, "Produk Tidak Tersedia");
                    namaProduk.setText(null);
                    hargaProduk.setText(null);
                }
            } catch (SQLException ex) {
                Logger.getLogger(transProduk.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new transProduk().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(transProduk.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(transProduk.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable Transaksi;
    private javax.swing.JButton cekDiskon;
    private javax.swing.JTextField diskon;
    private javax.swing.JTextField hargaProduk;
    private javax.swing.JTextField idKasir;
    private javax.swing.JTextField idProduk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahProduk;
    private javax.swing.JTextField namaProduk;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField total;
    // End of variables declaration                   
}
